obstacle_range: 1.0
raytrace_range: 1.5

footprint: [[-0.3, 0.25], [0.7, 0.25], [0.7, -0.25], [-0.3, -0.25]]

#footprint: [[-0.21, 0.31], [0.215, 0.31], [0.363, 0], [0.215, -0.31], [-0.21, -0.31]]

#footprint_padding: 0.06
robot_radius: 0.2
inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: lidar_1, data_type: LaserScan, topic: scan, marking: true, clearing: true}
