# Logitech Extreme 3D Pro
axis_linear: 1  # Forward/Back
scale_linear: 0.2
scale_linear_turbo: 0.3

axis_angular: 2  # Twist
scale_angular: 0.7
scale_angular: 1.0

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button